global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - 206.189.58.96:9090
    - 206.189.58.96:9100
    labels:
      group: prometheus
- job_name: m3
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - 206.189.58.96:7203
    - 206.189.58.96:9004
- job_name: consul_services
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  consul_sd_configs:
  - server: 127.0.0.1:8500
    datacenter: monitoring
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 1m
remote_write:
- url: http://localhost:7201/api/v1/prom/remote/write
  remote_timeout: 30s
  follow_redirects: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
  metadata_config:
    send: true
    send_interval: 1m
remote_read:
- url: http://localhost:7201/api/v1/prom/remote/read
  remote_timeout: 1m
  read_recent: true
  follow_redirects: true